ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
