ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
