ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vegetalte/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
